# image: eclipse-temurin:19.0.1_10-jdk-jammy

build-InfoService:
  allow_failure: true
  image: maven:latest
  stage: build
  tags:
    - docker-runner-1
  script:
    - rm -f .git/index.lock
    - ls -al
    - cd InfoService
    - mvn package -e -DskipTests --settings=settings.xml
    - echo "InfoService compile done"
    - pwd
    - ls -al ./target
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - InfoService/**/*
        - InfoService/*
        - CI_CD-Templates/trigger/*
  artifacts:
    paths:
      - ./
    expire_in: 1 day

deploy-InfoService:
  allow_failure: true
  variables:
    BRANCH_NM: develop
    SRVC_PORT: 8086
    SRVC_NAME: InfoService
    ARIF_FLDR: InfoServiceBuild
  image: docker:latest
  stage: deploy
  tags:
    - shell-runner-1
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - InfoService/**/*
        - InfoService/*
        - CI_CD-Templates/trigger/*    
  script:
    - pwd && ls -al
    - mkdir $ARIF_FLDR && cp -rf $SRVC_NAME/target/*.jar ./$ARIF_FLDR && cp -rf $SRVC_NAME/pom.xml ./$ARIF_FLDR && cp -rf $SRVC_NAME/src ./$ARIF_FLDR && ls -al && ls -al $ARIF_FLDR
    - SRVC_LCASE=$SRVC_NAME && SRVC_LCASE=$(echo "$SRVC_LCASE" | sed 's/.*/\L&/') && echo "$SRVC_LCASE"
    - docker build -f $SRVC_NAME/Dockerfile -t a-sber-$SRVC_LCASE-img:$BRANCH_NM .
    - docker rm -f a-sber-$SRVC_LCASE-container_$BRANCH_NM 2>/dev/null || exit 0
    - docker run -d -p $SRVC_PORT:$SRVC_PORT --network="host" --name a-sber-$SRVC_LCASE-container_$BRANCH_NM a-sber-$SRVC_LCASE-img:$BRANCH_NM
  dependencies:
    - build-InfoService

test-InfoService:
  rules:
    # - if: $CI_COMMIT_BRANCH == "develop"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - InfoService/**/*
        - InfoService/*
        - CI_CD-Templates/trigger/*
  allow_failure: true
  image: maven:latest
  # image: eclipse-temurin:17-jdk-alpine
  stage: test
  tags:
    - docker-runner-1
    # - shell-runner-1
  script:
    - rm -f .git/index.lock
    - ls -al
    - cd InfoService
    # - ls -al /usr/lib/jvm/
    - mvn -version
    - mvn test
    - echo "InfoService test done"  

deploy-InfoService-on-test-srv:
  variables:
    BRANCH_NM: develop
    SRVC_PORT: 8086
    SRVC_NAME: InfoService
    ARIF_FLDR: InfoServiceBuild
  image: docker:latest
  stage: deploy-on-test-srv
  tags:
    - shell-runner-java-test
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
      allow_failure: true
      changes:
        - InfoService/**/*
        - InfoService/*
        - CI_CD-Templates/trigger/*      
  script:
    - pwd && ls -al
    - mkdir $ARIF_FLDR && cp -rf $SRVC_NAME/target/*.jar ./$ARIF_FLDR && cp -rf $SRVC_NAME/pom.xml ./$ARIF_FLDR && cp -rf $SRVC_NAME/src ./$ARIF_FLDR && ls -al && ls -al $ARIF_FLDR
    - SRVC_LCASE=$SRVC_NAME && SRVC_LCASE=$(echo "$SRVC_LCASE" | sed 's/.*/\L&/') && echo "$SRVC_LCASE"
    - docker build -f $SRVC_NAME/Dockerfile -t a-sber-$SRVC_LCASE-img:$BRANCH_NM .
    - docker rm -f a-sber-$SRVC_LCASE-container_$BRANCH_NM 2>/dev/null || exit 0
    - docker run -d -p $SRVC_PORT:$SRVC_PORT --network="host" --name a-sber-$SRVC_LCASE-container_$BRANCH_NM a-sber-$SRVC_LCASE-img:$BRANCH_NM --log-driver=loki --log-opt loki-url="http://localhost:3100/loki/api/v1/push"
  dependencies:
    - build-InfoService
