server:
  port: ${PORT:8083}
eureka:
  instance:
    hostname: ${hostname:localhost}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
            - ModifyRequest=Added clientId
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposit/**
          filters:
            - RewritePath=/deposit/(?<path>.*), /$\{path}
            - ModifyRequest=Added clientId
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credit/**
          filters:
            - RewritePath=/credit/(?<path>.*), /$\{path}
            - ModifyRequest=Added clientId
        - id: money-transfer-service
          uri: lb://money-transfer-service
          predicates:
            - Path=/moneytransfer/**
          filters:
            - RewritePath=/moneytransfer/(?<path>.*), /$\{path}
            - ModifyRequest=Added clientId